CREATE TABLE overlays_users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_name TEXT NOT NULL UNIQUE,
user_password TEXT NOT NULL,
date_created TIMESTAMP DEFAULT now() NOT NULL
);



);


CREATE TABLE user_notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  note_owner INTEGER REFERENCES overlays_users(id) NOT NULL,
  from_topic INTEGER REFERENCES overlays_topics(id) NOT NULL,
  note_title TEXT NOT NULL,
  note_contents TEXT NOT NULL
);



