CREATE TABLE overlays_topics(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    topic_name TEXT NOT NULL,
    topic_url TEXT NOT NULL,
    note TEXT,
    date_added TIMESTAMP DEFAULT now() NOT NULL
);