CREATE TABLE overlays_users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_name TEXT NOT NULL UNIQUE,
password TEXT NOT NULL,
date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
)


ALTER TABLE overlays_server
  ADD COLUMN
    user_name INTEGER REFERENCES overlays_server(id) ON DELETE SET NULL;